### ISSUE TITLE
Release 0.10.0

### ISSUE THREAD

**Issue by goofansu** [elixir-wechat/wechat_pay#59]
@linjunpop Shall we make a new release?

**Comment by linjunpop** [comment]
🆒🚀

**Comment by goofansu** [comment]
@linjunpop I cannot publish release, can you do that? Thanks

**Comment by linjunpop** [comment]
As there's another change which makes `wechat_pay` requires Elixir > 1.10.

Let me publish a new version `0.10.0`.

**Comment by linjunpop** [comment]
🚀 https://hex.pm/packages/wechat_pay/0.10.0
